// frontend/src/services/mockData.js

/**
 * Mock data service for testing and development
 * Provides hardcoded data to simulate API responses
 */

// Mock playlist data similar to what would come from Spotify
export const mockPlaylistData = {
    id: 'test-playlist-id',
    name: 'Mock Testing Playlist',
    description: 'A mock playlist for testing purposes',
    owner: {
      id: 'mock-user',
      displayName: 'Test User'
    },
    images: [
      {
        url: 'https://via.placeholder.com/300'
      }
    ],
    tracks: [
      {
        id: 'track-1',
        name: 'Yellow Submarine',
        artists: [
          {
            id: 'artist-1',
            name: 'The Beatles'
          }
        ],
        album: {
          id: 'album-1',
          name: 'Revolver',
          releaseDate: '1966-08-05',
          images: [
            {
              url: 'https://via.placeholder.com/300'
            }
          ]
        },
        previewUrl: null,
        popularityScore: 80
      },
      {
        id: 'track-2',
        name: 'Bohemian Rhapsody',
        artists: [
          {
            id: 'artist-2',
            name: 'Queen'
          }
        ],
        album: {
          id: 'album-2',
          name: 'A Night at the Opera',
          releaseDate: '1975-11-21',
          images: [
            {
              url: 'https://via.placeholder.com/300'
            }
          ]
        },
        previewUrl: null,
        popularityScore: 90
      },
      {
        id: 'track-3',
        name: 'Billie Jean',
        artists: [
          {
            id: 'artist-3',
            name: 'Michael Jackson'
          }
        ],
        album: {
          id: 'album-3',
          name: 'Thriller',
          releaseDate: '1983-01-02',
          images: [
            {
              url: 'https://via.placeholder.com/300'
            }
          ]
        },
        previewUrl: null,
        popularityScore: 85
      },
      {
        id: 'track-4',
        name: 'Smells Like Teen Spirit',
        artists: [
          {
            id: 'artist-4',
            name: 'Nirvana'
          }
        ],
        album: {
          id: 'album-4',
          name: 'Nevermind',
          releaseDate: '1991-09-24',
          images: [
            {
              url: 'https://via.placeholder.com/300'
            }
          ]
        },
        previewUrl: null,
        popularityScore: 88
      },
      {
        id: 'track-5',
        name: 'Hotel California',
        artists: [
          {
            id: 'artist-5',
            name: 'Eagles'
          }
        ],
        album: {
          id: 'album-5',
          name: 'Hotel California',
          releaseDate: '1976-12-08',
          images: [
            {
              url: 'https://via.placeholder.com/300'
            }
          ]
        },
        previewUrl: null,
        popularityScore: 89
      }
    ],
    tracksCount: 5
  };
  
  // Mock questions similar to what would come from OpenAI
  export const mockGeneratedQuestions = [
    {
      question: "Beatles' yellow vessel in their 1966 song",
      answer: "SUBMARINE"
    },
    {
      question: "Queen song with 'Scaramouche, will you do the fandango?'",
      answer: "BOHEMIAN"
    },
    {
      question: "Michael Jackson song about a woman claiming 'the kid is not my son'",
      answer: "BILLIE"
    },
    {
      question: "Eagles' song about a place you can check out from but never leave",
      answer: "HOTEL"
    },
    {
      question: "Drummer for The Beatles",
      answer: "STARR"
    },
    {
      question: "Lead vocalist of Queen",
      answer: "MERCURY"
    },
    {
      question: "Michael Jackson album featuring 'Billie Jean'",
      answer: "THRILLER"
    },
    {
      question: "Nirvana's breakthrough album released in 1991",
      answer: "NEVERMIND"
    },
    {
      question: "First name of the guitarist for Eagles who sang 'Hotel California'",
      answer: "DON"
    },
    {
      question: "The 'Fab Four' band from Liverpool",
      answer: "BEATLES"
    },
    {
      question: "Queen's lead guitarist who built his own guitar",
      answer: "MAY"
    },
    {
      question: "Nirvana's lead singer and guitarist",
      answer: "COBAIN"
    },
    {
      question: "Michael Jackson's famous dance move",
      answer: "MOONWALK"
    },
    {
      question: "Eagles album featuring 'Hotel California'",
      answer: "HOTEL"
    },
    {
      question: "Genre of music pioneered by Nirvana",
      answer: "GRUNGE"
    }
  ];
  
  // Mock crossword data similar to what would be generated by crosswordService
  export const mockCrosswordData = {
    grid: {
      grid: [
        ['B', 'E', 'A', 'T', 'L', 'E', 'S', '', '', '', '', ''],
        ['', '', '', 'H', '', '', 'T', '', '', '', '', ''],
        ['', '', '', 'R', '', '', 'A', '', '', '', '', ''],
        ['H', 'O', 'T', 'I', 'L', '', 'R', '', '', '', '', ''],
        ['', '', '', 'L', '', '', 'R', '', '', '', '', ''],
        ['', '', '', 'L', '', 'G', 'R', 'U', 'N', 'G', 'E', ''],
        ['', '', '', 'E', '', '', '', '', '', '', '', ''],
        ['', '', '', 'R', '', '', '', '', '', '', '', ''],
        ['B', 'O', 'H', 'E', 'M', 'I', 'A', 'N', '', '', '', ''],
        ['', '', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', 'M', 'E', 'R', 'C', 'U', 'R', 'Y', '', ''],
        ['', '', '', '', '', '', '', '', '', '', '', ''],
        ['', '', '', '', '', 'C', 'O', 'B', 'A', 'I', 'N', '']
      ],
      bounds: {
        minRow: 0,
        minCol: 0,
        maxRow: 12,
        maxCol: 11
      }
    },
    entries: [
      {
        answer: "BEATLES",
        clue: "The 'Fab Four' band from Liverpool",
        position: {
          row: 0,
          col: 0
        },
        direction: "across",
        number: 1
      },
      {
        answer: "THRILLER",
        clue: "Michael Jackson album featuring 'Billie Jean'",
        position: {
          row: 0,
          col: 3
        },
        direction: "down",
        number: 2
      },
      {
        answer: "STARR",
        clue: "Drummer for The Beatles",
        position: {
          row: 0,
          col: 6
        },
        direction: "down",
        number: 3
      },
      {
        answer: "HOTEL",
        clue: "Eagles' song about a place you can check out from but never leave",
        position: {
          row: 3,
          col: 0
        },
        direction: "across",
        number: 4
      },
      {
        answer: "GRUNGE",
        clue: "Genre of music pioneered by Nirvana",
        position: {
          row: 5,
          col: 5
        },
        direction: "across",
        number: 5
      },
      {
        answer: "BOHEMIAN",
        clue: "Queen song with 'Scaramouche, will you do the fandango?'",
        position: {
          row: 8,
          col: 0
        },
        direction: "across",
        number: 6
      },
      {
        answer: "MERCURY",
        clue: "Lead vocalist of Queen",
        position: {
          row: 10,
          col: 3
        },
        direction: "across",
        number: 7
      },
      {
        answer: "COBAIN",
        clue: "Nirvana's lead singer and guitarist",
        position: {
          row: 12,
          col: 5
        },
        direction: "across",
        number: 8
      }
    ]
  };
  
  /**
   * Mock API functions to simulate backend services
   * These functions return Promises to mimic the async behavior of real API calls
   */
  export const mockSpotifyApi = {
    getPlaylistData: () => {
      return Promise.resolve({
        data: {
          data: mockPlaylistData
        }
      });
    }
  };
  
  export const mockQuestionApi = {
    generateQuestions: () => {
      return Promise.resolve({
        data: {
          data: {
            questions: mockGeneratedQuestions,
            count: mockGeneratedQuestions.length
          }
        }
      });
    }
  };
  
  export const mockCrosswordApi = {
    buildCrossword: () => {
      return Promise.resolve({
        data: {
          data: mockCrosswordData
        }
      });
    }
  };